### ISSUE TITLE
IOS can't run the camera to scan the QR_Code

### ISSUE THREAD

**Issue by AaronBear** [RonnyWeiss/APEX-QR-Code-Scanner#8] opened 2020-10-29 02:28 UTC
This APEX-Plug you developed is so nice . I find that it works well in Android but in IOS by Wechat

**Comment by RonnyWeiss** [comment] 2020-11-11 21:24
What do you mean in WeChat?

**Comment by RonnyWeiss** [comment] 2020-11-24 11:11
Closed because no reaction and bug could not be reproduced! Please reopen the ticket if issue still exists

**Comment by RonnyWeiss** [comment] 2020-12-08 22:46
fixed in Version 1.5

**Closed as completed by RonnyWeiss** 2020-12-08 22:46 UTC
